### GET Labels
POST {{host}}/api/v2/label/list
Content-Type: application/json
Authorization: Basic {{apiKey}} 

{
  "page" : 0,
  "pageSize" : 10,
  "searchText" : "",
  "orderBy" : "Name",
  "descending": false
}

###

### GET a single Label
GET {{host}}/api/v2/label/6396b7dd-f655-bc54-9fd8-8ae63808a28e
Content-Type: application/json
Authorization: Basic {{apiKey}}

###

 